#error
error.relation_ID_already_exists=The device ID already exists